"""Feedback loop module for continuous improvement."""

from walltrack.core.feedback.accuracy_models import (
    AccuracySnapshot,
    AccuracyTrend,
    AccuracyTrendAnalysis,
    FactorAccuracyBreakdown,
    RetrospectiveAnalysis,
    RetrospectiveOutcome,
    RetrospectiveSignal,
    SignalAccuracyMetrics,
    ThresholdAnalysis,
)
from walltrack.core.feedback.accuracy_tracker import AccuracyTracker, get_accuracy_tracker
from walltrack.core.feedback.backtest_models import (
    ApplySettingsRequest,
    ApplySettingsResult,
    BacktestConfig,
    BacktestProgress,
    BacktestResult,
    BacktestStatus,
    ExitStrategyConfig,
    ExitStrategyType,
    HistoricalSignal,
    MetricsComparison,
    PerformanceMetrics,
    PositionSizingConfig,
    ScoringWeights,
    SimulatedTrade,
    TradeComparison,
)
from walltrack.core.feedback.backtester import BacktestService, get_backtest_service
from walltrack.core.feedback.calibration_models import (
    ApplyWeightsRequest,
    AutoCalibrationConfig,
    CalibrationAnalysis,
    CalibrationStatus,
    CalibrationSuggestion,
    FactorCorrelation,
    ScoringFactor,
    WeightArchive,
    WeightSet,
    WeightSuggestion,
)
from walltrack.core.feedback.model_calibrator import ModelCalibrator, get_model_calibrator
from walltrack.core.feedback.models import (
    AggregateMetrics,
    ExitReason,
    TradeOutcome,
    TradeOutcomeCreate,
    TradeQuery,
    TradeQueryResult,
)
from walltrack.core.feedback.pattern_analyzer import PatternAnalyzer, get_pattern_analyzer
from walltrack.core.feedback.pattern_models import (
    ClusterPattern,
    Pattern,
    PatternAlert,
    PatternAnalysisResult,
    PatternSentiment,
    PatternType,
    SignificanceLevel,
    TimePattern,
    TokenPattern,
    WalletPattern,
)
from walltrack.core.feedback.performance_dashboard import (
    PerformanceDashboardService,
    get_dashboard_service,
)
from walltrack.core.feedback.performance_models import (
    BreakdownCategory,
    BreakdownType,
    BreakdownView,
    DashboardQuery,
    DateRange,
    KeyMetrics,
    PerformanceDashboardData,
    PeriodComparison,
    PnLTimeSeries,
    TimeGranularity,
    TimeSeriesPoint,
    WinRateTrend,
)
from walltrack.core.feedback.score_models import (
    BatchUpdateRequest,
    BatchUpdateResult,
    ScoreUpdateConfig,
    ScoreUpdateInput,
    ScoreUpdateResult,
    ScoreUpdateType,
    WalletMetrics,
    WalletScoreHistory,
)
from walltrack.core.feedback.score_updater import WalletScoreUpdater, get_score_updater
from walltrack.core.feedback.trade_recorder import TradeRecorder, get_trade_recorder

__all__ = [
    "AccuracySnapshot",
    "AccuracyTracker",
    "AccuracyTrend",
    "AccuracyTrendAnalysis",
    "AggregateMetrics",
    "ApplySettingsRequest",
    "ApplySettingsResult",
    "ApplyWeightsRequest",
    "AutoCalibrationConfig",
    "BacktestConfig",
    "BacktestProgress",
    "BacktestResult",
    "BacktestService",
    "BacktestStatus",
    "BatchUpdateRequest",
    "BatchUpdateResult",
    "BreakdownCategory",
    "BreakdownType",
    "BreakdownView",
    "CalibrationAnalysis",
    "CalibrationStatus",
    "CalibrationSuggestion",
    "ClusterPattern",
    "DashboardQuery",
    "DateRange",
    "ExitReason",
    "ExitStrategyConfig",
    "ExitStrategyType",
    "FactorAccuracyBreakdown",
    "FactorCorrelation",
    "HistoricalSignal",
    "KeyMetrics",
    "MetricsComparison",
    "ModelCalibrator",
    "Pattern",
    "PatternAlert",
    "PatternAnalysisResult",
    "PatternAnalyzer",
    "PatternSentiment",
    "PatternType",
    "PerformanceDashboardData",
    "PerformanceDashboardService",
    "PerformanceMetrics",
    "PeriodComparison",
    "PnLTimeSeries",
    "PositionSizingConfig",
    "RetrospectiveAnalysis",
    "RetrospectiveOutcome",
    "RetrospectiveSignal",
    "ScoreUpdateConfig",
    "ScoreUpdateInput",
    "ScoreUpdateResult",
    "ScoreUpdateType",
    "ScoringFactor",
    "ScoringWeights",
    "SignalAccuracyMetrics",
    "SignificanceLevel",
    "SimulatedTrade",
    "ThresholdAnalysis",
    "TimeGranularity",
    "TimePattern",
    "TimeSeriesPoint",
    "TokenPattern",
    "TradeComparison",
    "TradeOutcome",
    "TradeOutcomeCreate",
    "TradeQuery",
    "TradeQueryResult",
    "TradeRecorder",
    "WalletMetrics",
    "WalletPattern",
    "WalletScoreHistory",
    "WalletScoreUpdater",
    "WeightArchive",
    "WeightSet",
    "WeightSuggestion",
    "WinRateTrend",
    "get_accuracy_tracker",
    "get_backtest_service",
    "get_dashboard_service",
    "get_model_calibrator",
    "get_pattern_analyzer",
    "get_score_updater",
    "get_trade_recorder",
]
