"""Decay event data models for tracking wallet performance degradation.

This module provides Pydantic models for decay events that track changes
in wallet performance status (decay, recovery, consecutive losses, dormancy).

Story 3.4 - Wallet Decay Detection
"""

from datetime import datetime
from decimal import Decimal
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field, field_validator


class DecayEventType(str, Enum):
    """Type of decay event (AC4).

    Values:
        DECAY_DETECTED: Rolling win rate fell below threshold (AC1)
        RECOVERY: Flagged wallet recovered above threshold (AC1)
        CONSECUTIVE_LOSSES: 3+ consecutive losses detected (AC2)
        DORMANCY: No activity for 30+ days (AC3)
    """

    DECAY_DETECTED = "decay_detected"
    RECOVERY = "recovery"
    CONSECUTIVE_LOSSES = "consecutive_losses"
    DORMANCY = "dormancy"


class DecayEventCreate(BaseModel):
    """Model for creating a new decay event (insert operation).

    Used when creating decay events in the repository. ID and created_at
    are auto-generated by the database.

    Attributes:
        wallet_address: Wallet that experienced decay event.
        event_type: Type of decay event.
        rolling_win_rate: Win rate over most recent 20 trades (0.00-1.00).
        lifetime_win_rate: Overall win rate across all trades (0.00-1.00).
        consecutive_losses: Number of consecutive losses at time of event.
        score_before: Wallet score before adjustment (0.0000-1.0000).
        score_after: Wallet score after adjustment (0.0000-1.0000).

    Example:
        >>> event = DecayEventCreate(
        ...     wallet_address="9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
        ...     event_type=DecayEventType.DECAY_DETECTED,
        ...     rolling_win_rate=Decimal("0.35"),
        ...     lifetime_win_rate=Decimal("0.62"),
        ...     consecutive_losses=0,
        ...     score_before=Decimal("0.8500"),
        ...     score_after=Decimal("0.6800"),
        ... )
    """

    wallet_address: str = Field(..., min_length=32, max_length=44)
    event_type: DecayEventType
    rolling_win_rate: Decimal | None = Field(None, ge=0, le=1)
    lifetime_win_rate: Decimal | None = Field(None, ge=0, le=1)
    consecutive_losses: int = Field(0, ge=0)
    score_before: Decimal | None = Field(None, ge=0, le=1)
    score_after: Decimal | None = Field(None, ge=0, le=1)

    @field_validator("rolling_win_rate", "lifetime_win_rate", mode="before")
    @classmethod
    def validate_win_rates(cls, v):
        """Ensure win rates are None or valid Decimal."""
        if v is None:
            return None
        if isinstance(v, float):
            return Decimal(str(v))
        return v

    @field_validator("score_before", "score_after", mode="before")
    @classmethod
    def validate_scores(cls, v):
        """Ensure scores are None or valid Decimal."""
        if v is None:
            return None
        if isinstance(v, float):
            return Decimal(str(v))
        return v


class DecayEvent(DecayEventCreate):
    """Full decay event model (includes database-generated fields).

    Extends DecayEventCreate with id and created_at fields that are
    populated by the database after insertion.

    Attributes:
        id: UUID primary key (auto-generated).
        created_at: Timestamp when event was logged (auto-generated).

    Example:
        >>> event = DecayEvent(
        ...     id=UUID("550e8400-e29b-41d4-a716-446655440000"),
        ...     wallet_address="9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
        ...     event_type=DecayEventType.RECOVERY,
        ...     rolling_win_rate=Decimal("0.55"),
        ...     lifetime_win_rate=Decimal("0.65"),
        ...     consecutive_losses=0,
        ...     score_before=Decimal("0.6800"),
        ...     score_after=Decimal("0.7480"),
        ...     created_at=datetime(2025, 12, 30, 12, 0, 0),
        ... )
    """

    id: UUID
    created_at: datetime

    model_config = {"from_attributes": True}
