"""Constants module."""

from walltrack.constants.solana import (
    ASSOCIATED_TOKEN_PROGRAM_ID,
    COMPUTE_UNIT_LIMIT,
    LAMPORTS_PER_SOL,
    MAX_TRANSACTION_SIZE,
    SOL_DECIMALS,
    TOKEN_PROGRAM_ID,
    WSOL_MINT,
)
from walltrack.constants.webhook import (
    HELIUS_SIGNATURE_HEADER,
    HMAC_ALGORITHM,
    KNOWN_DEX_PROGRAMS,
    MAX_PROCESSING_TIME_MS,
    MAX_SOLANA_ADDRESS_LENGTH,
    MIN_SOLANA_ADDRESS_LENGTH,
    SPL_TOKEN_2022_PROGRAM,
    SPL_TOKEN_PROGRAM,
    WEBHOOK_TIMEOUT_SECONDS,
    WRAPPED_SOL_MINT,
)

__all__ = [
    # Solana
    "WSOL_MINT",
    "SOL_DECIMALS",
    "LAMPORTS_PER_SOL",
    "TOKEN_PROGRAM_ID",
    "ASSOCIATED_TOKEN_PROGRAM_ID",
    "MAX_TRANSACTION_SIZE",
    "COMPUTE_UNIT_LIMIT",
    # Webhook
    "HELIUS_SIGNATURE_HEADER",
    "HMAC_ALGORITHM",
    "KNOWN_DEX_PROGRAMS",
    "MAX_PROCESSING_TIME_MS",
    "SPL_TOKEN_2022_PROGRAM",
    "SPL_TOKEN_PROGRAM",
    "WEBHOOK_TIMEOUT_SECONDS",
    "WRAPPED_SOL_MINT",
]
